# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias cdquery='cd ~/Algorithm/ShopOptimize/scripts/'
export PATH=$PATH:~/miniprog/tools
export PS1="\u@\H \W$ "
