# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias cdshop='cd ~/Algorithm/ShopOptimize/scripts/'
alias cdquery='cd ~/Algorithm/QueryAll/queryall'
alias cdprog='cd ~/miniprog/python'
export PATH=$PATH:~/miniprog/tools
export PS1="\u@\H \W$ "
export RABBITMQ_CONFIG_FILE=~/rabbitmq/config/rabbitmq
export RABBITMQ_SERVER_ERL_ARGS="-setcookie rabbit"
export RABBITMQ_CTL_ERL_ARGS="-setcookie rabbit"
export RABBITMQ_MNESIA_BASE=~/rabbitmq/data
export RABBITMQ_LOG_BASE=~/rabbitmq/log
export RABBITMQ_ENABLED_PLUGINS_FILE=~/rabbitmq/etc/rabbitmq/enabled_plugins
