# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias cdshop='cd ~/Algorithm/ShopOptimize/scripts/'
alias cdquery='cd ~/Algorithm/QueryAll/queryall'
alias cdprog='cd ~/miniprog/python'
export PATH=$PATH:~/miniprog/tools
export PS1="\u@\H \W$ "
