(defun foo (n)
    (lambda (i) (incf n i)))

(format t "~a~%" (foo 2))
;(format t "~a~%" ( (foo 2) 2 ))
(setq a nil)
(push 4 a)
(push 5 a)
(format t "~a~%" (pop a))
a
(format t "~d~o~b~9~%" 100 100 100 100)
(format t "~a~a~a~a~%" 100 100 100 100)
(format *query-io* "output message")
(force-output *query-io*)
(format t "~a~%" "output message")
(format t "~a~%" "output message")
(format t "~%")
(format t "~a:!`0t~a~%":author "berlinix")
(format t "~a~%" "helloworld")
(format t "~a~a~%" "helloworld" 100)
(format t "~a~%" '(1 2))
(format t "~a~%" (first '(1 2 3)))
(format t "~a~%" (rest '(1 2 3)))
(format t "~a~%" (cons '4 '(1 2 3)))
(format t "~a~%" (list '4 '(1 2 3)))
(format t "~a~%" (append '(4) '(1 2 3)))
