/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.xiaomi.miui.ad.thrift.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class MiuiAdStoreServiceLogFictionEventDetail implements TBase<MiuiAdStoreServiceLogFictionEventDetail, MiuiAdStoreServiceLogFictionEventDetail._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("MiuiAdStoreServiceLogFictionEventDetail");

  private static final TField SCRIBE_INFO_FIELD_DESC = new TField("scribeInfo", TType.STRUCT, (short)1);
  private static final TField LOG_TYPE_FIELD_DESC = new TField("logType", TType.STRING, (short)2);
  private static final TField EVENT_TYPE_FIELD_DESC = new TField("eventType", TType.STRING, (short)3);
  private static final TField IMEI_FIELD_DESC = new TField("imei", TType.STRING, (short)4);
  private static final TField BOOK_ID_FIELD_DESC = new TField("bookId", TType.STRING, (short)5);
  private static final TField BOOK_NAME_FIELD_DESC = new TField("bookName", TType.STRING, (short)6);
  private static final TField PACKAGE_NAME_FIELD_DESC = new TField("packageName", TType.STRING, (short)7);
  private static final TField BOOK_NUM_FIELD_DESC = new TField("bookNum", TType.I64, (short)8);
  private static final TField PRICE_FIELD_DESC = new TField("price", TType.I64, (short)9);

  private MiuiLogScribeInfo scribeInfo;
  private String logType;
  private String eventType;
  private String imei;
  private String bookId;
  private String bookName;
  private String packageName;
  private long bookNum;
  private long price;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    SCRIBE_INFO((short)1, "scribeInfo"),
    LOG_TYPE((short)2, "logType"),
    EVENT_TYPE((short)3, "eventType"),
    IMEI((short)4, "imei"),
    BOOK_ID((short)5, "bookId"),
    BOOK_NAME((short)6, "bookName"),
    PACKAGE_NAME((short)7, "packageName"),
    BOOK_NUM((short)8, "bookNum"),
    PRICE((short)9, "price");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SCRIBE_INFO
          return SCRIBE_INFO;
        case 2: // LOG_TYPE
          return LOG_TYPE;
        case 3: // EVENT_TYPE
          return EVENT_TYPE;
        case 4: // IMEI
          return IMEI;
        case 5: // BOOK_ID
          return BOOK_ID;
        case 6: // BOOK_NAME
          return BOOK_NAME;
        case 7: // PACKAGE_NAME
          return PACKAGE_NAME;
        case 8: // BOOK_NUM
          return BOOK_NUM;
        case 9: // PRICE
          return PRICE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BOOKNUM_ISSET_ID = 0;
  private static final int __PRICE_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SCRIBE_INFO, new FieldMetaData("scribeInfo", TFieldRequirementType.DEFAULT, 
        new StructMetaData(TType.STRUCT, MiuiLogScribeInfo.class)));
    tmpMap.put(_Fields.LOG_TYPE, new FieldMetaData("logType", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.EVENT_TYPE, new FieldMetaData("eventType", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.IMEI, new FieldMetaData("imei", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.BOOK_ID, new FieldMetaData("bookId", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.BOOK_NAME, new FieldMetaData("bookName", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.PACKAGE_NAME, new FieldMetaData("packageName", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.BOOK_NUM, new FieldMetaData("bookNum", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I64)));
    tmpMap.put(_Fields.PRICE, new FieldMetaData("price", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(MiuiAdStoreServiceLogFictionEventDetail.class, metaDataMap);
  }

  public MiuiAdStoreServiceLogFictionEventDetail() {
  }

  public MiuiAdStoreServiceLogFictionEventDetail(
    MiuiLogScribeInfo scribeInfo,
    String logType,
    String eventType,
    String imei,
    String bookId,
    String bookName,
    String packageName,
    long bookNum,
    long price)
  {
    this();
    this.scribeInfo = scribeInfo;
    this.logType = logType;
    this.eventType = eventType;
    this.imei = imei;
    this.bookId = bookId;
    this.bookName = bookName;
    this.packageName = packageName;
    this.bookNum = bookNum;
    setBookNumIsSet(true);
    this.price = price;
    setPriceIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MiuiAdStoreServiceLogFictionEventDetail(MiuiAdStoreServiceLogFictionEventDetail other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetScribeInfo()) {
      this.scribeInfo = new MiuiLogScribeInfo(other.scribeInfo);
    }
    if (other.isSetLogType()) {
      this.logType = other.logType;
    }
    if (other.isSetEventType()) {
      this.eventType = other.eventType;
    }
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetBookId()) {
      this.bookId = other.bookId;
    }
    if (other.isSetBookName()) {
      this.bookName = other.bookName;
    }
    if (other.isSetPackageName()) {
      this.packageName = other.packageName;
    }
    this.bookNum = other.bookNum;
    this.price = other.price;
  }

  public MiuiAdStoreServiceLogFictionEventDetail deepCopy() {
    return new MiuiAdStoreServiceLogFictionEventDetail(this);
  }

  @Override
  public void clear() {
    this.scribeInfo = null;
    this.logType = null;
    this.eventType = null;
    this.imei = null;
    this.bookId = null;
    this.bookName = null;
    this.packageName = null;
    setBookNumIsSet(false);
    this.bookNum = 0;
    setPriceIsSet(false);
    this.price = 0;
  }

  public MiuiLogScribeInfo getScribeInfo() {
    return this.scribeInfo;
  }

  public void setScribeInfo(MiuiLogScribeInfo scribeInfo) {
    this.scribeInfo = scribeInfo;
  }

  public void unsetScribeInfo() {
    this.scribeInfo = null;
  }

  /** Returns true if field scribeInfo is set (has been asigned a value) and false otherwise */
  public boolean isSetScribeInfo() {
    return this.scribeInfo != null;
  }

  public void setScribeInfoIsSet(boolean value) {
    if (!value) {
      this.scribeInfo = null;
    }
  }

  public String getLogType() {
    return this.logType;
  }

  public void setLogType(String logType) {
    this.logType = logType;
  }

  public void unsetLogType() {
    this.logType = null;
  }

  /** Returns true if field logType is set (has been asigned a value) and false otherwise */
  public boolean isSetLogType() {
    return this.logType != null;
  }

  public void setLogTypeIsSet(boolean value) {
    if (!value) {
      this.logType = null;
    }
  }

  public String getEventType() {
    return this.eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }

  public void unsetEventType() {
    this.eventType = null;
  }

  /** Returns true if field eventType is set (has been asigned a value) and false otherwise */
  public boolean isSetEventType() {
    return this.eventType != null;
  }

  public void setEventTypeIsSet(boolean value) {
    if (!value) {
      this.eventType = null;
    }
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been asigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getBookId() {
    return this.bookId;
  }

  public void setBookId(String bookId) {
    this.bookId = bookId;
  }

  public void unsetBookId() {
    this.bookId = null;
  }

  /** Returns true if field bookId is set (has been asigned a value) and false otherwise */
  public boolean isSetBookId() {
    return this.bookId != null;
  }

  public void setBookIdIsSet(boolean value) {
    if (!value) {
      this.bookId = null;
    }
  }

  public String getBookName() {
    return this.bookName;
  }

  public void setBookName(String bookName) {
    this.bookName = bookName;
  }

  public void unsetBookName() {
    this.bookName = null;
  }

  /** Returns true if field bookName is set (has been asigned a value) and false otherwise */
  public boolean isSetBookName() {
    return this.bookName != null;
  }

  public void setBookNameIsSet(boolean value) {
    if (!value) {
      this.bookName = null;
    }
  }

  public String getPackageName() {
    return this.packageName;
  }

  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }

  public void unsetPackageName() {
    this.packageName = null;
  }

  /** Returns true if field packageName is set (has been asigned a value) and false otherwise */
  public boolean isSetPackageName() {
    return this.packageName != null;
  }

  public void setPackageNameIsSet(boolean value) {
    if (!value) {
      this.packageName = null;
    }
  }

  public long getBookNum() {
    return this.bookNum;
  }

  public void setBookNum(long bookNum) {
    this.bookNum = bookNum;
    setBookNumIsSet(true);
  }

  public void unsetBookNum() {
    __isset_bit_vector.clear(__BOOKNUM_ISSET_ID);
  }

  /** Returns true if field bookNum is set (has been asigned a value) and false otherwise */
  public boolean isSetBookNum() {
    return __isset_bit_vector.get(__BOOKNUM_ISSET_ID);
  }

  public void setBookNumIsSet(boolean value) {
    __isset_bit_vector.set(__BOOKNUM_ISSET_ID, value);
  }

  public long getPrice() {
    return this.price;
  }

  public void setPrice(long price) {
    this.price = price;
    setPriceIsSet(true);
  }

  public void unsetPrice() {
    __isset_bit_vector.clear(__PRICE_ISSET_ID);
  }

  /** Returns true if field price is set (has been asigned a value) and false otherwise */
  public boolean isSetPrice() {
    return __isset_bit_vector.get(__PRICE_ISSET_ID);
  }

  public void setPriceIsSet(boolean value) {
    __isset_bit_vector.set(__PRICE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SCRIBE_INFO:
      if (value == null) {
        unsetScribeInfo();
      } else {
        setScribeInfo((MiuiLogScribeInfo)value);
      }
      break;

    case LOG_TYPE:
      if (value == null) {
        unsetLogType();
      } else {
        setLogType((String)value);
      }
      break;

    case EVENT_TYPE:
      if (value == null) {
        unsetEventType();
      } else {
        setEventType((String)value);
      }
      break;

    case IMEI:
      if (value == null) {
        unsetImei();
      } else {
        setImei((String)value);
      }
      break;

    case BOOK_ID:
      if (value == null) {
        unsetBookId();
      } else {
        setBookId((String)value);
      }
      break;

    case BOOK_NAME:
      if (value == null) {
        unsetBookName();
      } else {
        setBookName((String)value);
      }
      break;

    case PACKAGE_NAME:
      if (value == null) {
        unsetPackageName();
      } else {
        setPackageName((String)value);
      }
      break;

    case BOOK_NUM:
      if (value == null) {
        unsetBookNum();
      } else {
        setBookNum((Long)value);
      }
      break;

    case PRICE:
      if (value == null) {
        unsetPrice();
      } else {
        setPrice((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SCRIBE_INFO:
      return getScribeInfo();

    case LOG_TYPE:
      return getLogType();

    case EVENT_TYPE:
      return getEventType();

    case IMEI:
      return getImei();

    case BOOK_ID:
      return getBookId();

    case BOOK_NAME:
      return getBookName();

    case PACKAGE_NAME:
      return getPackageName();

    case BOOK_NUM:
      return new Long(getBookNum());

    case PRICE:
      return new Long(getPrice());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SCRIBE_INFO:
      return isSetScribeInfo();
    case LOG_TYPE:
      return isSetLogType();
    case EVENT_TYPE:
      return isSetEventType();
    case IMEI:
      return isSetImei();
    case BOOK_ID:
      return isSetBookId();
    case BOOK_NAME:
      return isSetBookName();
    case PACKAGE_NAME:
      return isSetPackageName();
    case BOOK_NUM:
      return isSetBookNum();
    case PRICE:
      return isSetPrice();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MiuiAdStoreServiceLogFictionEventDetail)
      return this.equals((MiuiAdStoreServiceLogFictionEventDetail)that);
    return false;
  }

  public boolean equals(MiuiAdStoreServiceLogFictionEventDetail that) {
    if (that == null)
      return false;

    boolean this_present_scribeInfo = true && this.isSetScribeInfo();
    boolean that_present_scribeInfo = true && that.isSetScribeInfo();
    if (this_present_scribeInfo || that_present_scribeInfo) {
      if (!(this_present_scribeInfo && that_present_scribeInfo))
        return false;
      if (!this.scribeInfo.equals(that.scribeInfo))
        return false;
    }

    boolean this_present_logType = true && this.isSetLogType();
    boolean that_present_logType = true && that.isSetLogType();
    if (this_present_logType || that_present_logType) {
      if (!(this_present_logType && that_present_logType))
        return false;
      if (!this.logType.equals(that.logType))
        return false;
    }

    boolean this_present_eventType = true && this.isSetEventType();
    boolean that_present_eventType = true && that.isSetEventType();
    if (this_present_eventType || that_present_eventType) {
      if (!(this_present_eventType && that_present_eventType))
        return false;
      if (!this.eventType.equals(that.eventType))
        return false;
    }

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_bookId = true && this.isSetBookId();
    boolean that_present_bookId = true && that.isSetBookId();
    if (this_present_bookId || that_present_bookId) {
      if (!(this_present_bookId && that_present_bookId))
        return false;
      if (!this.bookId.equals(that.bookId))
        return false;
    }

    boolean this_present_bookName = true && this.isSetBookName();
    boolean that_present_bookName = true && that.isSetBookName();
    if (this_present_bookName || that_present_bookName) {
      if (!(this_present_bookName && that_present_bookName))
        return false;
      if (!this.bookName.equals(that.bookName))
        return false;
    }

    boolean this_present_packageName = true && this.isSetPackageName();
    boolean that_present_packageName = true && that.isSetPackageName();
    if (this_present_packageName || that_present_packageName) {
      if (!(this_present_packageName && that_present_packageName))
        return false;
      if (!this.packageName.equals(that.packageName))
        return false;
    }

    boolean this_present_bookNum = true;
    boolean that_present_bookNum = true;
    if (this_present_bookNum || that_present_bookNum) {
      if (!(this_present_bookNum && that_present_bookNum))
        return false;
      if (this.bookNum != that.bookNum)
        return false;
    }

    boolean this_present_price = true;
    boolean that_present_price = true;
    if (this_present_price || that_present_price) {
      if (!(this_present_price && that_present_price))
        return false;
      if (this.price != that.price)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_scribeInfo = true && (isSetScribeInfo());
    builder.append(present_scribeInfo);
    if (present_scribeInfo)
      builder.append(scribeInfo);

    boolean present_logType = true && (isSetLogType());
    builder.append(present_logType);
    if (present_logType)
      builder.append(logType);

    boolean present_eventType = true && (isSetEventType());
    builder.append(present_eventType);
    if (present_eventType)
      builder.append(eventType);

    boolean present_imei = true && (isSetImei());
    builder.append(present_imei);
    if (present_imei)
      builder.append(imei);

    boolean present_bookId = true && (isSetBookId());
    builder.append(present_bookId);
    if (present_bookId)
      builder.append(bookId);

    boolean present_bookName = true && (isSetBookName());
    builder.append(present_bookName);
    if (present_bookName)
      builder.append(bookName);

    boolean present_packageName = true && (isSetPackageName());
    builder.append(present_packageName);
    if (present_packageName)
      builder.append(packageName);

    boolean present_bookNum = true;
    builder.append(present_bookNum);
    if (present_bookNum)
      builder.append(bookNum);

    boolean present_price = true;
    builder.append(present_price);
    if (present_price)
      builder.append(price);

    return builder.toHashCode();
  }

  public int compareTo(MiuiAdStoreServiceLogFictionEventDetail other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MiuiAdStoreServiceLogFictionEventDetail typedOther = (MiuiAdStoreServiceLogFictionEventDetail)other;

    lastComparison = Boolean.valueOf(isSetScribeInfo()).compareTo(typedOther.isSetScribeInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScribeInfo()) {
      lastComparison = TBaseHelper.compareTo(this.scribeInfo, typedOther.scribeInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLogType()).compareTo(typedOther.isSetLogType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogType()) {
      lastComparison = TBaseHelper.compareTo(this.logType, typedOther.logType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventType()).compareTo(typedOther.isSetEventType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventType()) {
      lastComparison = TBaseHelper.compareTo(this.eventType, typedOther.eventType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImei()).compareTo(typedOther.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = TBaseHelper.compareTo(this.imei, typedOther.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBookId()).compareTo(typedOther.isSetBookId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookId()) {
      lastComparison = TBaseHelper.compareTo(this.bookId, typedOther.bookId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBookName()).compareTo(typedOther.isSetBookName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookName()) {
      lastComparison = TBaseHelper.compareTo(this.bookName, typedOther.bookName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPackageName()).compareTo(typedOther.isSetPackageName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPackageName()) {
      lastComparison = TBaseHelper.compareTo(this.packageName, typedOther.packageName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBookNum()).compareTo(typedOther.isSetBookNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookNum()) {
      lastComparison = TBaseHelper.compareTo(this.bookNum, typedOther.bookNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrice()).compareTo(typedOther.isSetPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrice()) {
      lastComparison = TBaseHelper.compareTo(this.price, typedOther.price);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // SCRIBE_INFO
          if (field.type == TType.STRUCT) {
            this.scribeInfo = new MiuiLogScribeInfo();
            this.scribeInfo.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // LOG_TYPE
          if (field.type == TType.STRING) {
            this.logType = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // EVENT_TYPE
          if (field.type == TType.STRING) {
            this.eventType = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // IMEI
          if (field.type == TType.STRING) {
            this.imei = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // BOOK_ID
          if (field.type == TType.STRING) {
            this.bookId = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // BOOK_NAME
          if (field.type == TType.STRING) {
            this.bookName = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // PACKAGE_NAME
          if (field.type == TType.STRING) {
            this.packageName = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // BOOK_NUM
          if (field.type == TType.I64) {
            this.bookNum = iprot.readI64();
            setBookNumIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 9: // PRICE
          if (field.type == TType.I64) {
            this.price = iprot.readI64();
            setPriceIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.scribeInfo != null) {
      oprot.writeFieldBegin(SCRIBE_INFO_FIELD_DESC);
      this.scribeInfo.write(oprot);
      oprot.writeFieldEnd();
    }
    if (this.logType != null) {
      oprot.writeFieldBegin(LOG_TYPE_FIELD_DESC);
      oprot.writeString(this.logType);
      oprot.writeFieldEnd();
    }
    if (this.eventType != null) {
      oprot.writeFieldBegin(EVENT_TYPE_FIELD_DESC);
      oprot.writeString(this.eventType);
      oprot.writeFieldEnd();
    }
    if (this.imei != null) {
      oprot.writeFieldBegin(IMEI_FIELD_DESC);
      oprot.writeString(this.imei);
      oprot.writeFieldEnd();
    }
    if (this.bookId != null) {
      oprot.writeFieldBegin(BOOK_ID_FIELD_DESC);
      oprot.writeString(this.bookId);
      oprot.writeFieldEnd();
    }
    if (this.bookName != null) {
      oprot.writeFieldBegin(BOOK_NAME_FIELD_DESC);
      oprot.writeString(this.bookName);
      oprot.writeFieldEnd();
    }
    if (this.packageName != null) {
      oprot.writeFieldBegin(PACKAGE_NAME_FIELD_DESC);
      oprot.writeString(this.packageName);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(BOOK_NUM_FIELD_DESC);
    oprot.writeI64(this.bookNum);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(PRICE_FIELD_DESC);
    oprot.writeI64(this.price);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MiuiAdStoreServiceLogFictionEventDetail(");
    boolean first = true;

    sb.append("scribeInfo:");
    if (this.scribeInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.scribeInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("logType:");
    if (this.logType == null) {
      sb.append("null");
    } else {
      sb.append(this.logType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventType:");
    if (this.eventType == null) {
      sb.append("null");
    } else {
      sb.append(this.eventType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("imei:");
    if (this.imei == null) {
      sb.append("null");
    } else {
      sb.append(this.imei);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bookId:");
    if (this.bookId == null) {
      sb.append("null");
    } else {
      sb.append(this.bookId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bookName:");
    if (this.bookName == null) {
      sb.append("null");
    } else {
      sb.append(this.bookName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("packageName:");
    if (this.packageName == null) {
      sb.append("null");
    } else {
      sb.append(this.packageName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bookNum:");
    sb.append(this.bookNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("price:");
    sb.append(this.price);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

