default:
	javac -cp /usr/share/java/tomcat-servlet-api-3.0.jar HelloWorldServlet.java
	cp HelloWorldServlet.class ../WEB-INF/
clean:
	rm -rf HelloWorldServlet.class ../WEB-INF/HelloWorldServlet.class
